name: 'Github Actions for UrlSubmit'

on:
  push:
  schedule:
    - cron: '0 23 * * 6'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Requirements
        run: |
          - python -m pip install --upgrade pip
          - pip install flake8 pytest
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Submit Url
        run: python urlSubmit.py https://blog.yuanpei.me
