name: 'Github Actions for UrlSubmit'

on:
  push:
  schedule:
    - cron: '0 23 * * 6'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Requirements
        run: |
          - python -m pip install pip -U
          - python -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - python -m pip install -r requirements.txt
      - name: Submit Url
        run: python3 urlSubmit.py
